{{- range .Values.topics }}
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  partitionCount: {{ .partitions }}
  replicas: {{ .replicas }}
  configs:
    cleanup.policy: {{ .configs.cleanupPolicy }}
  kafkaClusterRef:
    name: {{ $.Values.kafka.name }}
    namespace: {{ $.Values.namespace }}
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: dummy.topic
spec:
  name: dummy.topic
  configs:
    min.insync.replicas: '2'
    retention.ms: '-1'
  partitionCount: 1
  replicas: 3
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default

{{- end }}