apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: {{ .Values.schemaRegistry.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.schemaRegistry.replicas }}
  image:
    application: {{ .Values.images.registry }}
    init: {{ .Values.images.init }}
{{/*  tls:*/}}
{{/*    secretRef: tls-schema-registry*/}}
  dependencies:
    kafka:
      bootstrapEndpoint: {{ .Values.kafka.name }}.{{.Values.namespace}}.svc.cluster.local:9071
{{/*      authentication:*/}}
{{/*        type: mtls*/}}
{{/*      tls:*/}}
{{/*        enabled: true*/}}
