apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  namespace: {{ .Values.namespace }}
spec:
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
  configs:
    cleanup.policy: {{ .Values.topic.configs.cleanupPolicy }}
  kafkaClusterRef:
    name: {{ .Values.kafka.name }}
    namespace: {{ .Values.namespace }}